# Generated by Django 2.2 on 2021-02-20 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall_app', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='message_id',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='user',
        ),
    ]
