# Generated by Django 2.2 on 2021-02-11 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0004_authors_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='books',
            field=models.ManyToManyField(related_name='authors', to='books_authors_app.Books'),
        ),
    ]
